### ISSUE TITLE
Support Django 3.x

### ISSUE THREAD

**Issue by CuriousLearner** [niwinz/django-sites#13]
Support for Django 3.x is to be added.

**Comment by justinmboucher** [comment]
From what I can tell the only thing that needs to change is in the utils.py file:
```
from django.contrib.staticfiles.templatetags.staticfiles import static as _static
```
Change to:
```
from django.templatetags.static import static as _static
```

Django 3 moved static templatetags to their builtin templatetags. So it throws a **No module named: 'django.contrib.staticfiles.templatetags'** exception. Tested on my dev system, and it seems to work without any other issues now.

**Comment by CuriousLearner** [comment]
Hi @justinmboucher 

Yes, the pull request that is attached to this issue handles this in the library. Please let me know what do you think about #12

**Comment by theskumar** [comment]
The patch need to be merged and released @niwinz pinging on this.

**Comment by theskumar** [comment]
@niwinz Just a friendly reminder. Would it be possible to merge and release this?

**Comment by CuriousLearner** [comment]
With #12 , this has been fixed.

0.11 is released on pypi: https://pypi.org/project/django-sites/0.11/ and tagged on git with https://github.com/niwinz/django-sites/releases/tag/0.11
